package codeemoji.core;

public enum CEModifier {
    //classes
    PUBLIC_CLASS,
    ABSTRACT_CLASS,
    FINAL_CLASS,
    DEFAULT_CLASS,
    //fields
    PUBLIC_FIELD,
    PROTECTED_FIELD,
    DEFAULT_FIELD,
    PRIVATE_FIELD,
    FINAL_FIELD,
    STATIC_FIELD,
    TRANSIENT_FIELD,
    VOLATILE_FIELD,
    //methods
    PUBLIC_METHOD,
    PROTECTED_METHOD,
    DEFAULT_METHOD,
    PRIVATE_METHOD,
    STATIC_METHOD,
    FINAL_METHOD,
    ABSTRACT_METHOD,
    SYNCHRONIZED_METHOD,
    NATIVE_METHOD,
    DEFAULT_INTERFACE_METHOD
}
